app/blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog', __name__, template_folder='templates')

app/blog/routes.py
import os
import shutil
from app import db
from flask import current_app, render_template, abort, Response, request, redirect, url_for, flash, jsonify, make_response
from flask_login import current_user, login_required
from datetime import datetime

from app.models import Post
from app.forms import PostForm, EmptyForm
from .persist_img import persist_img
from .unique_slugify import unique_slugify

from . import blog


@blog.route('/posts', methods=['GET'])
def view_all():
    """ Returns all blog post entries """
    page = request.args.get('page', 1, type=int)

    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for(
        'blog.view_all', page=posts.next_num) if posts.has_next else None
    prev_url = url_for(
        'blog.view_all', page=posts.prev_num) if posts.has_prev else None

    return render_template("all_posts.html", title='Flask Project | Blog', posts=posts.items, next_url=next_url,
                           prev_url=prev_url, page_num=posts.page, page_count=posts.pages)


@blog.route('/create-post', methods=['GET', 'POST'])
@login_required
def create_post():
    """ 
    Create_post endpoint.
    Creates the post form and saves blog entry to database. 
    """

    form = PostForm()

    # Check if this is a tinyMce image upload.
    if request.method == 'POST':
        if request.files.get('file'):
            try:
                file = persist_img(request.files.get('file'), tinymce_upload=True)
            except Exception as err:
                print("ERROR with: ", err)
                abort(404)
                # Return image path back to editor
            return jsonify({'location': file})

    # POST request
    if form.validate_on_submit():
        post = Post(
            slug=unique_slugify(form.title.data),
            title=form.title.data,
            description=form.description.data,
            date_of_visit=datetime(int(form.year.data), int(
                form.month.data), int(form.day.data)),
            rating=form.rating.data,
            author=current_user
        )
        # Flush to get post id
        db.session.add(post)
        db.session.flush()

        img_file = request.files['img_file']
        if img_file:
            image = persist_img(img_file, form=form, post=post)
            db.session.add(image)

        db.session.commit()

        flash('Your post is now live!')

        # Respond to POST request with a redirect. - Avoids browser confirming duplicate submission.
        return redirect(url_for('main.index'))

    return render_template('create_post.html', title='Create a new blog post', form=form)


@blog.route('/post/<slug>')
def post_detail(slug):
    """ Return full post entry update view count """
    post = Post.query.filter_by(slug=slug).first_or_404()
    
    # Update the view count.  Check post has attribute.
    # If admin edits an article and slug changes whilst a user is reading the current argument
    # An AttributeError 'NoneType' will be thrown.  Check current object has the view_count attr.
    if hasattr(post, 'view_count'):
        post.view_count += 1
        db.session.add(post)
        db.session.commit()

    # Hero image object.  If no image saved return None.  Jinja will test
    # and not include the hero section when rendering.
    try:
        hero = post.image[0]
    except IndexError:
        hero = None

    return render_template('article.html', title=post.title, post=post, hero=hero)


@blog.route('/edit-post/<slug>', methods=['GET', 'POST'])
@login_required
def edit_post(slug):
    """ Edits an existing blog entry """

    post = Post.query.filter_by(slug=slug).first()
    form = PostForm(obj=post)

    try: existing_hero = post.image[0]
    except IndexError: existing_hero = None

    if request.method == 'GET':
        # Set the select field (drop down menu) values for a get request.
        form.day.data = post.date_of_visit.strftime('%-d')
        form.month.data = post.date_of_visit.strftime('%-m')
        form.year.data = post.date_of_visit.strftime('%-Y')

    if form.validate_on_submit():
        form.populate_obj(post)

        post.date_of_visit = datetime(int(form.year.data), int(
            form.month.data), int(form.day.data))

        # Check if user has uploaded a new hero/banner image; and update.
        img_file = request.files['img_file']
        new_image = persist_img(img_file, form=form, post=post) if img_file else None
        
        if new_image:
            
            # Check if an existing image is on disk and remove/replace.
            if existing_hero:
                # Remove hero image data from database
                db.session.delete(existing_hero)
               
                # Remove file from disk
                os.remove(existing_hero.abs_path) 

            db.session.add(new_image)
        
        db.session.commit()
        return redirect(url_for('main.user', username=current_user.username))

    return render_template('create_post.html', title=post.title, form=form)


@blog.route('/delete-post/<post_id>', methods=['POST'])
@login_required
def delete_post(post_id):
    """ Deletes a post entry """

    form = EmptyForm()

    if form.validate_on_submit():
        post = Post.query.get(post_id)

        # Check the current user owns the post to prevent unauthorised deleting of users posts.
        if post.author == current_user:
            try:
                # Remove post directory and image from disk.
                shutil.rmtree(post.image[0].post_dir)
            except OSError as e:
                print(f"Error: {e.filename} - {e.strerror}")
            
            db.session.delete(post)
            db.session.commit()

    return redirect(url_for('main.user', username=current_user.username))

app/blog/templates/_confirm_delete_modal.html
<!-- Confirm delete modal begin-->
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">

        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title text-danger font-weight-bold">Confirm delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <p>Are you sure you want to permanently delete the post titled:</p>
                <p id="modal-delete-post-title"></p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">Cancel</button>

                <!-- CSRF form, submit & confirm delete -->
                <form id="delete-post-form" method="POST">
                    {{ form.hidden_tag() }}
                    <button type="submit" class="btn btn-danger">Delete post</button>
                </form>
            </div>

        </div>
    </div>
</div>
<!--confirm delete modal end-->

app/blog/templates/_paginate.html
{% if prev_url %}
<a href="{{ prev_url }}">Newer posts</a>
{% endif %}
{% if next_url %}
<a href="{{ next_url }}">Older posts</a>
{% endif %}

app/blog/templates/_rating.html
{% for _ in range(0, post.rating) %}&#11088; {% endfor %}

app/blog/templates/all_posts.html
{% extends 'base.html' %}

{% block content %}
<section class="color-section section-shadow">
    <div class="container">
        <div>
            <h1 class="big-heading">Blog</h1>
            <hr class="hr-navy">
            <p>Take a look at all the entries we have posted so far.</p>
        </div>
    </div>
</section>

<div class="container">
    {% for post in posts %}
    <h2 class="heading mb-0 navy">{{ post.title }}</h2>
    <p>{% include '_rating.html' %}</p>
    <p>{{ post.snippet() }}
        <a href="{{ url_for('blog.post_detail', slug=post.slug) }}">Continue reading</a></p>
    <hr class="hr-navy">
    {% endfor %}

    {% if page_count > 1 and page_num <= page_count %}
    <nav class="mt-5">
        <ul class="pagination justify-content-center">
            <li class="page-item {% if not prev_url %}disabled{% endif %}">
                <a class="page-link" href="{{ prev_url }}">Newer posts</a></li>
            <li class="page-item {% if not next_url %}disabled{% endif %}">
                <a class="page-link" href="{{ next_url }}" tabindex="{% if not next_url %}-1{% endif %}">Older posts</a>
            </li>
        </ul>
        <p class="text-center">Page: {{page_num}} of {{page_count}}</p>
    </nav>
    {% endif %}
    {% if page_num > page_count %}
    <p>Invalid page request</p>
    <a href="{{ url_for('blog.view_all')}}">Go back</a>
    {% endif %}
</div>
{% endblock content %}

app/blog/templates/article.html
{% extends 'base.html' %}

{% block content %}

<section id="article">

    <section class="color-section">
        <div class="container">
            <div>
                <h1 class="big-heading">{{ post.title }}</h1>
                <h2 class="sub-heading">Rating: {% include '_rating.html' %}</h2>
                <hr class="hr-navy">
                <div class="line-spacing-small">
                    <p class="color-lg">Written by: {{ post.author.full_name() }} </p>
                    <p class="color-lg">{{ post.get_date_created() }}</p>
                    <br>
                    <p class="word-count font-weight-bold"></p>

                    <div class="fb-like" data-href="#" data-width=""
                        data-layout="button" data-action="like" data-size="large" data-share="true">like_button_here
                    </div>
                    <br>
                </div>
            </div>
        </div>
    </section>

    <!--------------------- Hero --------------------->
    {% if hero %}
    <section>
        <div class="hero-article shadow" style="background-image: url( {{ hero.img_url }} )"
            aria-label="{{ hero.img_alt }}">
        </div>
    </section>
    {% endif %}

    <section>
        <div class="container">
            <div class="clearfix">
                <h3 class="heading navy">&#128221; Description</h3>
                <p>{{ post.description|safe }}</p>
            </div>
        </div>
    </section>

</section>
{% endblock content %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/est-reading-time.min.js') }}"></script>
{% endblock scripts %}

app/blog/templates/create_post.html
{% extends 'base.html' %}
{% block content %}
    <section class="mt-20 color-section">
        <div class="container">
            <h1>Hi, {{ current_user.first_name.title() }}</h1>
            <h2>Feeling creative?</h2>

            <hr>

            <form autocomplete="off" action="" method="POST" enctype="multipart/form-data">

                {{ form.hidden_tag() }}

                <div>
                    {{ form.title.label }} <br>
                    {{ form.title(class_="form-control create-post") }}<br>
                </div>
                <hr>
                <div>
                    {{ form.rating.label }} <br>
                    {{ form.rating(class_="form-control") }}<br>
                </div>
                <hr>
                <div>
                    {{ form.description.label }} <br>
                    {{ form.description(class_="form-control create-post") }}
                </div>
                <hr>
                <p>Day of visit</p>
                <div>
                    {{ form.day.label }} <br>
                    {{ form.day(class_="form-control") }}
                    {{ form.month.label }}<br>
                    {{ form.month(class_="form-control") }}
                    {{ form.year.label }}
                    {{ form.year(class_="form-control") }}
                </div>
                <hr>
                <div>
                    <div>
                        {{ form.img_file.label }}<br>
                        {{ form.img_file(class_="form-control") }}<br>
                    </div>
                    <div>
                        {{ form.img_alt.label }}<br>
                        {{ form.img_alt(class_="form-control") }}<br>
                    </div>
                </div>

                <hr>
                <div>{{ form.submit() }}</div>

            </form>
        </div>
    </section>
{% endblock content %}
{% block scripts %}
    <!-- tinyMCE editor -->
    <script src="https://cdn.tiny.cloud/1/jzu57niocq8zjp4at7kl2gho68bt55bycbu7oe772ikykypq/tinymce/5/tinymce.min.js"
            referrerpolicy="origin"></script>
    <!-- tinyMCE init -->
    <script src="{{ url_for('static', filename='js/tinyMceInit.min.js') }}"></script>
{% endblock scripts %}

app/blog/templates/dashboard.html
{% extends 'base.html' %}
{% block content %}

<section class="color-section">
    <div class="container text-right">
        {% if user == current_user %}
        <h1 class="heading mt-navy">Hi, {{ user.first_name.title() }}</h1>
        {% else %}
        <h1 class="heading mt-navy">{{ user.full_name() }}</h1>
        {% endif %}

        {% if user.about_me %}
        <p>
            {{ user.about_me }}
            {% endif %}
        </p>
        <p>
            {% if user.last_seen %}
            last seen on: {{ user.get_last_seen() }}
        </p>
        {% endif %}

        <hr>
        <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>
        <p>
            {% if user == current_user %}
            <a href="{{ url_for('main.edit_profile') }}">Edit your profile</a></p>

        <hr>

        {% elif not current_user.is_following(user) %}
        <p>
        <form action="{{ url_for('follow', username=user.username) }}" method="post">
            {{ form.hidden_tag() }}
            {{ form.submit(value='Follow') }}
        </form>
        </p>
        {% else %}
        <p>
        <form action="{{ url_for('unfollow', username=user.username) }}" method="post">
            {{ form.hidden_tag() }}
            {{ form.submit(value='Unfollow') }}
        </form>
        </p>
        {% endif %}

    </div>
</section>

<section>
    <div class="container">

        {% for post in posts %}

        <div class="card mb-3 shadow">
            <h5 class="card-header color-section">{{ post.title|safe }}</h5>
            <div class="card-body">
                <p><strong>Viewed:</strong> {{ post.view_count }}</p>
                <p class="card-title"><strong>Date created:</strong> {{ post.get_date_created()|safe }}</p>
                <p class="card-text">{{ post.snippet()|safe }}</p>

                <div style="display: flex;">
                    <!-- Edit Post -->
                    <form action="{{ url_for('blog.edit_post', slug=post.slug) }}" method="GET">
                        <button class="btn btn-primary m-1">Edit post</button>
                    </form>

                    <!-- Delete Post - triggers confirmation modal -->
                    <button type="button" class="btn btn-danger m-1" data-toggle="modal" data-target="#confirmDeleteModal"
                        data-post-id="{{ post.id }}" data-post-title="{{ post.title }}"
                        data-post-created="{{ post.get_date_created() }}">Delete post</button>
                </div>
            </div>
        </div>

        {% endfor %}

        {% include '_confirm_delete_modal.html' %}

        <!-- Pagination begin -->
        {% include '_paginate.html'%}
        <!-- Pagination end -->

    </div>
</section>
{% endblock content %}
{% block scripts %}
    <script src="{{ url_for('static', filename='js/deletePostModal.min.js') }}"></script>
{% endblock scripts %}