app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates')

app/main/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, current_app, send_from_directory
from flask_login import current_user, login_required
from app import db
from app.models import User, Post

# Forms
from app.forms import EditProfileForm, EmptyForm, ContactForm

# Blueprint
from app.main import main

from app.email import send_email


@main.before_request
def before_request():
    """ A function that fires before every request.  """
    if current_user.is_authenticated:
        # Update the users last_seen field.
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@main.route('/robots.txt', methods=['GET'])
def send_from_static():
    """ Send files directly from static dir """
    return send_from_directory(current_app.static_folder, request.path[1:])


@main.route('/')
@main.route('/index')
def index():
    """ Index endpoint. """

    # Limit the posts displayed on the index page.
    posts = Post.query.order_by(Post.timestamp.desc()).limit(4)

    return render_template('index.html', title='Homepage | index.html', posts=posts)


@main.route('/explore')
@login_required
def explore():
    """ 
    Explore endpoint.
    Explore new content or find new friends/followers
    """
    # In this example..
    # Explore all users content.  Find all posts by all users and sort by timestamp

    # Pagination - .paginate(<starting from>, <number of items per page>, <bool>)
    # <bool> True returns a 404 error when out of range, False returns empty list.
    # Page defaults to 1 if if request.args returns None.

    # Pagination returns a Pagination object with a property 'items'

    page = request.args.get('page', 1, type=int)

    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for(
        'main.explore', page=posts.next_num) if posts.has_next else None
    prev_url = url_for(
        'main.explore', page=posts.prev_num) if posts.has_prev else None

    return render_template("explore.html", title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)


@main.route('/user/<username>')
@login_required
def user(username):
    # If username does not exist trigger 404 error.

    # Get current user.
    usr = User.query.filter_by(username=username).first_or_404()

    # Set page number, return 1 as a default.
    page = request.args.get('page', 1, type=int)

    # Get all posts by current user.
    posts = usr.posts.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)

    # Create next and previous url
    next_url = url_for('main.user', username=usr.username,
                       page=posts.next_num) if posts.has_next else None
    prev_url = url_for('main.user', username=usr.username,
                       page=posts.prev_num) if posts.has_prev else None

    # Create an EmptyForm - protects against CSRF.
    form = EmptyForm()

    return render_template('dashboard.html', user=usr, posts=posts.items, form=form,
                           next_url=next_url, prev_url=prev_url)


@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    """ Edit users profile endpoint. """

    # Create the edit profile form.
    form = EditProfileForm()

    # POST Request
    if form.validate_on_submit():
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash("Your changes have been saved.")
        return redirect(url_for('main.edit_profile'))
    elif request.method == 'GET':
        form.about_me.data = current_user.about_me

    return render_template('edit_profile.html', title='Edit Profile', form=form)


@main.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):
    """ Add user to your friends/follow list """

    form = EmptyForm()

    if form.validate_on_submit():
        usr = User.query.filter_by(username=username).first()
        if usr is None:
            flash(f'User: {username} not found. ')
            return redirect(url_for('main.index'))
        if usr == current_user:
            flash('You cannot follow yourself')
            return redirect(url_for('main.user', username=username))

        # Add the specified user to your follow/friends list.
        current_user.follow(usr)

        # Commit to db
        db.session.commit()

        flash(f'You are now following {username}')

        return redirect(url_for('main.user', username=username))

    else:
        # If CSRF token is missing or invalid, redirect.
        return redirect(url_for('main.index'))


@main.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    """ Remove a user from your friends/follow list """

    form = EmptyForm()
    if form.validate_on_submit():
        usr = User.query.filter_by(username=username).first()
        if usr is None:
            flash(f'User {username} not found.')
            return redirect(url_for('main.index'))
        if usr == current_user:
            flash('You cannot unfollow yourself!')
            return redirect(url_for('main.user', username=username))
        current_user.unfollow(usr)
        db.session.commit()
        flash(f'You are not following {username}.')
        return redirect(url_for('main.user', username=username))
    else:
        return redirect(url_for('main.index'))


@main.route('/contact', methods=['GET', 'POST'])
def contact():
    """ Contact page view """
    form = ContactForm()
    if form.validate_on_submit():
        send_email(
            subject=current_app.config['WEBSITE_FORM_SUBJECT'],
            sender=current_app.config['ADMINS'][0],
            recipients=current_app.config['CLIENT_EMAIL'],
            text_body=render_template(
                'email/contact_form.txt',
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                email=form.email.data,
                number=form.number.data,
                message=form.message.data),
            html_body=render_template(
                'email/contact_form.html',
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                email=form.email.data,
                number=form.number.data,
                message=form.message.data),
        )

        flash("Message sent - Thanks for being awesome!! 🦄")
        return redirect(url_for('main.index'))
    return render_template('contact.html', title="Contact Us", form=form)

app/main/templates/_home_banner.html
<!--------------------- Hero --------------------->
<section>
    <div class="hero shadow"
         style="background-image: url('{{ url_for('static', filename='img/Flask_logo.png') }}')">
        <div class="container">

            <div class="hero-title-text text-center">
                <h1 class="big-heading mb-5">Flask Project</h1>
                <div class="homepage-btn-group">
                    <a href="{{ url_for('blog.view_all') }}">
                        <button class="btn btn-solid-yellow btn-lg shadow" type="button">View blog</button>
                    </a>
                    <a href="#about">
                        <button class="btn btn-solid-yellow btn-lg" type="button">About me</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

app/main/templates/_scripts.html
    <!-- Bootstrap scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>

app/main/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <link rel="preload" as="style"
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Montserrat:wght@400;700;900&display=swap"
          onload="this.rel='stylesheet'" />
    <link rel="preload" as="style" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"
        onload="this.rel='stylesheet'"/>
    <link rel="preload" as="style" href="{{ url_for('static', filename='css/styles.css') }}"
        onload="this.rel='stylesheet'" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

    {% if title %}<title>{{ title }}</title>{% else %}<title>Flask Project</title>{% endif %}

    <meta name="Description"
        content="Flask Project.">
</head>

<body>
    <!------------------ Navigation ------------------>

    <section id="navigation" class="color-section">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark">
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Flask Project</a>

                <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <div class="navbar-nav ml-auto">
                        <a class="nav-link ml-auto" href="{{ url_for('main.index') }}">Home</a>
                        <a class="nav-link ml-auto" href="{{ url_for('blog.view_all') }}">Blog</a>
                        <a class="nav-link ml-auto" href="{{ url_for('main.contact') }}">Contact</a>

                        {% if current_user.is_anonymous %}
                        <a class="nav-link ml-auto" href="{{ url_for('auth.login') }}">Login</a>
                        {% else %}
                        <a class="nav-link ml-auto"
                            href="{{ url_for('main.user', username=current_user.username) }}">Dashboard</a>
                        <a class="nav-link ml-auto" href="{{ url_for('blog.create_post') }}">Create Post</a>
                        <a class="nav-link ml-auto" href="{{ url_for('auth.logout') }}">Logout</a>
                        {% endif %}

                        {% if current_user.is_anonymous %}
                        <a class="nav-link ml-auto" href="{{ url_for('auth.register') }}">Sign Up</a>
                        {% endif %}

                    </div>
                </div>
            </nav>
        </div>
    </section>

    <!------------------ Flash messages ------------------>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <section id="flash-msg" class="color-section">
        <div class="container">
            <ul>
                {% for message in messages %}
                <div class="alert alert-danger shadow" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </ul>
        </div>
    </section>
    {% endif %}
    {% endwith %}

    <!------------------ Block Content Begin ------------------>
    {% block content %}{% endblock content %}

    <!------------------ Footer ------------------>

    {% include 'footer.html' %}

    <!------------------ Scripts ------------------>
    {% include '_scripts.html' %}
    {% block scripts %}{% endblock scripts %}
</body>

</html>

app/main/templates/base_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="{{ url_for('static', filename='css/signin.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/hero.css') }}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Montserrat:wght@400;700;900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/v4-shims.css">
</head>
<body class="color-section">
<section id="navigation" class="color-section">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Flask Project</a>

            <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse"
                data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="navbar-nav ml-auto">
                    <a class="nav-link ml-auto" href="{{ url_for('main.index') }}">Home</a>
                    <a class="nav-link ml-auto" href="{{ url_for('blog.view_all') }}">Blog</a>
                    <a class="nav-link ml-auto" href="{{ url_for('main.contact') }}">Contact</a>

                    {% if current_user.is_anonymous %}
                    <a class="nav-link ml-auto" href="{{ url_for('auth.login') }}">Login</a>
                    {% else %}
                    <a class="nav-link ml-auto"
                        href="{{ url_for('main.user', username=current_user.username) }}">Dashboard</a>
                    <a class="nav-link ml-auto" href="{{ url_for('blog.create_post') }}">Create Post</a>
                    <a class="nav-link ml-auto" href="{{ url_for('auth.logout') }}">Logout</a>
                    {% endif %}

                    {% if current_user.is_anonymous %}
                    <a class="nav-link ml-auto" href="{{ url_for('auth.register') }}">Sign Up</a>
                    {% endif %}
                    
                </div>
            </div>
        </nav>
    </div>
</section>
{% block content %}{% endblock %}
{% include '_scripts.html' %}
</body>

app/main/templates/contact.html
{% extends "base.html" %}
{% block content %}
<section class="color-section">
    <div class="container">
        <h1 class="big-heading">Contact Page</h1>
        <hr class="hr-navy">
        <p>Contact sub heading️
        </p>
    </div>
</section>

<section>
    <div class="container">
        <form action="" method="POST">
            {{ form.csrf_token }}

            <div class="form-row mb-4">
                <div class="col">
                    <p class='mb-0 heading navy'>{{ form.first_name.label }}</p>
                    {{ form.first_name(class_="form-control") }}
                    {% for error in form.first_name.errors %}
                    <strong class="form-error">Error</strong>{% endfor %}
                </div>
                <div class="col">
                    <p class='mb-0 heading navy'>{{ form.last_name.label }}</p>
                    {{ form.last_name(class_="form-control")}}
                    {% for error in form.last_name.errors %}
                    <strong class="form-error">Error: {{ error }}</strong>{% endfor %}
                </div>
            </div>

            <div class="mb-4">
                <p class='mb-0 heading navy'>{{ form.email.label }}</p>{{ form.email(class_="form-control") }}
                {% for error in form.email.errors %}
                <strong class="form-error">Error {{ error }}</strong>{% endfor %}
            </div>

            <div class="mb-4">
                <p class='mb-0 heading navy'>{{ form.number.label }}</p>{{ form.number(class_="form-control") }}
                {% for error in form.number.errors %}
                <strong class="form-error">Error {{ error }}</strong>{% endfor %}
            </div>

            <div class="mb-4">
                <p class='mb-4 heading navy'>{{ form.message.label }}</p>
                {{ form.message(class_="form-control", rows=10) }}
                {% for error in form.message.errors %}
                <strong class="form-error">Error</strong>{% endfor %}
            </div>

            {{ form.submit(class_="btn btn-solid-pink shadow") }}
        </form>
    </div>
    <div class="container">
        <hr class="hr-navy mt-0">
        <p class="heading navy">Email: <a class="" href="mailto:hello@example.com?subject=Flask Project Website Enquiry">hello@example.com</a></p>
        <p class="heading navy">Facebook: <a class="" href="https://facebook.com/">Facebook Page</a></p>
        <p class="heading navy">Messenger: <a class="" href="https://m.me/">Facebook messenger</a></p>
        <p class="heading navy">Instagram: <a class="" href="https://www.instagram.com/">@InstaPage</a></p>
    </div>
</section>


{% endblock content %}

app/main/templates/edit_profile.html
{% extends 'base.html' %}
{% block content %}
<h1>Edit Profile</h1>
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <p>
        {{ form.about_me.label }}<br>
        {{ form.about_me(cols=50, rows=4) }}<br>

        {% for error in form.about_me.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.submit() }}
    </p>
</form>
{% endblock content %}

app/main/templates/explore.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

<h1>Find Friends or explore new content</h1>
<p> Todo! </p>
<hr>
<h2>Example showing: Posts by all users</h2>


        {% for post in posts %}
        <p>{{ post.snippet() }}</p>
        {% endfor %}

        {% if prev_url %}
        <a href="{{ prev_url }}">Newer posts</a>
        {% endif %}
        {% if next_url %}
        <a href="{{ next_url }}">Older posts</a>
        {% endif %}
</div>

    {% endblock content %}

app/main/templates/footer.html
<footer id="footer" class="white-section p-3">
  <div class="text-center">
    <p>
      <a href="https://www.facebook.com/">
        <i class="text-black p-4 fa fa-facebook" aria-hidden="true"></i>
      </a>

      <a href="https://www.instagram.com/">
        <i class="text-black p-4 fa fa-instagram" aria-hidden="true"></i>
      </a>

      <a href="{{ url_for('main.contact') }}"><i class="text-black p-4 fa fa-envelope" aria-hidden="true"></i></a>
    </p>
    <p class="text-secondary">Copyright &copy; {{ current_year }}</p>
  </div>
</footer>

app/main/templates/index.html
{% extends "base.html" %}
{% block content %}
    {% include '_home_banner.html' %}

    <!------------------ Blog Posts Template ------------------>
    <section class="white-section">
        <div class="container">

            <div class="d-flex align-items-center">
                <h2 class="heading navy mb-0">Latest posts</h2>

                <div class="ml-auto">
                    <p>Social buttons</p>
                </div>
            </div>

            <br>
            <div class="card-deck">

                {% for post in posts %}
                    <div class="col-lg-6 col-md-6 mb-5 p-0">
                        <div class="card h-100 shadow">
                            <div class="card-header color-section">
                                <h3 class="mb-0 mt-navy heading">{{ post.title }}</h3>
                            </div>
                            <div class="card-body">
                                <p>
                                    {{ post.snippet()|safe }}
                                </p>
                                <a href="{{ url_for('blog.post_detail', slug=post.slug) }}">continue reading.</a>
                            </div>
                            <div class="card-footer color-section">

                                <div class="d-flex align-items-center">
                                    <div class="mb-0 mr-auto date">{{ post.get_date_created() }}</div>
                                    <div class="mb-0">{% for _ in range(0, post.rating) %}&#11088; {% endfor %}</div>
                                </div>

                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a href="{{ url_for('blog.view_all') }}">
                <button class="btn btn-solid-yellow btn-lg shadow" type="button">View all
                    posts
                </button>
            </a>
        </div>
    </section>

    <!------------------ About ------------------>
    <section id="about" class="color-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 align-self-center">
                    <h2 class="heading mt-navy">Heading</h2>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Orci sagittis eu volutpat odio facilisis. Tempor id eu nisl nunc mi ipsum
                    faucibus. Fermentum posuere urna nec tincidunt. Sed risus pretium quam vulputate dignissim
                    suspendisse. Eros donec ac odio tempor orci dapibus. Egestas dui id ornare arcu odio ut sem nulla.
                    Pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Urna et pharetra pharetra massa
                    massa. Ullamcorper eget nulla facilisi etiam dignissim. At augue eget arcu dictum varius.
                    Pellentesque elit eget gravida cum sociis natoque. Vitae auctor eu augue ut lectus arcu bibendum.
                    Amet luctus venenatis lectus magna fringilla urna. Senectus et netus et malesuada fames ac turpis
                    egestas maecenas. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Netus et
                    malesuada fames ac turpis egestas maecenas pharetra. Pellentesque eu tincidunt tortor aliquam nulla
                    facilisi cras. Justo eget magna fermentum iaculis. At erat pellentesque adipiscing commodo.
                    <br><br>
                    Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Venenatis a condimentum
                    vitae sapien pellentesque. Sed augue lacus viverra vitae congue eu consequat ac felis. Id donec
                    ultrices tincidunt arcu non sodales. Mattis ullamcorper velit sed ullamcorper morbi tincidunt. Cum
                    sociis natoque penatibus et magnis dis parturient. Penatibus et magnis dis parturient montes
                    nascetur ridiculus mus mauris. Ipsum suspendisse ultrices gravida dictum. Purus gravida quis blandit
                    turpis cursus in hac. Morbi tincidunt augue interdum velit euismod in pellentesque massa. Aliquam
                    purus sit amet luctus venenatis lectus magna. Massa tincidunt nunc pulvinar sapien et ligula
                    ullamcorper malesuada proin. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Dolor sed
                    viverra ipsum nunc aliquet.
                </div>

                <div class="col-lg-6 text-center align-self-center">
                    <img src="{{ url_for('static', filename='img/Flask_logo.png') }}"
                         alt="Flask Project" class="section-img">

                    <p class="mt-3">Flask Project: Registration, Login and blog features.></p>
                </div>
            </div>
        </div>
    </section>

    <section class="white-section">
        <div class="container">
            <h2 class="heading navy">Heading</h2>
            <p> Nullam vehicula ipsum a arcu cursus vitae. Consectetur purus ut faucibus pulvinar elementum integer
                enim neque volutpat. Pellentesque nec nam aliquam sem et. Sed viverra tellus in hac habitasse platea
                dictumst vestibulum. Maecenas pharetra convallis posuere morbi. Mattis enim ut tellus elementum
                sagittis vitae et leo duis. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Leo
                a diam sollicitudin tempor id eu. Mollis nunc sed id semper risus. Viverra justo nec ultrices dui
                sapien eget. Integer eget aliquet nibh praesent tristique magna sit amet purus. Orci dapibus
                ultrices in iaculis nunc sed augue lacus viverra. Interdum posuere lorem ipsum dolor sit amet
                consectetur. Feugiat sed lectus vestibulum mattis ullamcorper. Quisque non tellus orci ac auctor
                augue mauris. Viverra nibh cras pulvinar mattis nunc sed. Diam donec adipiscing tristique risus nec
                feugiat. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Nunc aliquet bibendum
                enim facilisis gravida neque convallis a.
            </p>
            <a href="https://www.facebook.com/">
                <i class="fa fa-facebook fa-3x mr-5" aria-hidden="true"></i>
            </a>
            <a href="https://www.instagram.com/">
                <i class="fa fa-instagram fa-3x" aria-hidden="true"></i>
            </a>
        </div>
    </section>

    <!------------------ Call to action ------------------>
    <section id="collab-cta" class="color-section">
        <div class="container">
            <div>
                <h1 class="big-heading">Big Heading!</h1>
                <p>I love python and micro frameworks rock!</p>
                <a href="#">
                    <button class="btn btn-solid-yellow shadow"
                            type="button">Random Button
                    </button>
                </a>
            </div>
        </div>
    </section>
{% endblock content %}